import os
from fpdf import FPDF
from datetime import datetime

class PDFReport(FPDF):
    def header(self):
        self.set_font("Arial", 'B', 15)
        self.set_text_color(0, 212, 255) # Cyan header
        self.cell(0, 10, 'FinAgentX - Official Trade Statement', 0, 1, 'C')
        self.line(10, 22, 200, 22)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_trade_statement(ticker: str, amount: float, user_email: str) -> str:
    """Generates a PDF statement and returns the file path."""
    pdf = PDFReport()
    pdf.add_page()
    
    # Title
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 15, f'Trade Execution: {ticker.upper()}', 0, 1, 'L')
    
    # Meta Info
    pdf.set_font("Arial", '', 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f'Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 1, 'L')
    pdf.cell(0, 8, f'User: {user_email}', 0, 1, 'L')
    pdf.cell(0, 8, f'Transaction ID: TXN-{datetime.now().strftime("%y%m%d%H%M%S")}', 0, 1, 'L')
    pdf.ln(10)
    
    # Details Box
    pdf.set_fill_color(240, 248, 255)
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, 'Transaction Details', 0, 1, 'L', fill=True)
    
    pdf.set_font("Arial", '', 12)
    pdf.cell(90, 10, 'Asset:', 1)
    pdf.cell(100, 10, f'{ticker.upper()} Equity', 1, 1)
    
    pdf.cell(90, 10, 'Action:', 1)
    pdf.cell(100, 10, 'BUY', 1, 1)
    
    pdf.cell(90, 10, 'Total Invested:', 1)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(100, 10, f'INR {amount:,.2f}', 1, 1)
    
    pdf.ln(15)
    pdf.set_font("Arial", 'I', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 6, "This is an automated receipt generated by FinAgentX. The transaction was approved by the AI Investment Committee and executed via simulated clearing. Thank you for using FinAgentX.")
    
    # Ensure directory exists
    os.makedirs('statements', exist_ok=True)
    filename = f"statements/Statement_{ticker}_{datetime.now().strftime('%H%M%S')}.pdf"
    
    pdf.output(filename)
    return filename
